apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-service-account
  namespace: issue-microservices
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::452968854315:role/melric-sqs-role # Create message role

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: aws-load-balancer-controller
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::452968854315:role/melric-iam-eks-role-lb-controller # Load balancers to assume this role