apiVersion: v1
kind: ServiceAccount
metadata:
  name: ses-backend-service-account # Note this acts as a middleman to the real role to assume
  namespace: issue-microservices
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::452968854315:role/melric-ses-sqs-role # SQS Read and Delete